language: cpp

compiler:
  - clang

script:
  - make tests


notifications:
  email:
    recipients:
      - mengyzhang87@gmail.com
    on_success: always
    on_failure: always  
  slack: nyuoop:Pt31RgSKx7T34S8fyZ4NI7tj
    on_failure: never
